services:
  fabric:
    image: itzg/minecraft-server
    container_name: minecraft
    restart: unless-stopped
    stdin_open: true
    tty: true
    environment:
      EULA: true
      TYPE: FABRIC
      CREATE_CONSOLE_IN_PIPE: true
      INIT_MEMORY: 4G
      MAX_MEMORY: 16G
    ports:
      - 25565:25565
    volumes:
      - ./data:/data

